### ISSUE TITLE
Usage in CF modpacks?

### ISSUE THREAD

**Issue by raspmary** [davidjjung/milkyway#1]
i'd absolutely love to have this mod in my pack, but the pack is only on curseforge while the mod is only on modrinth - are curseforge packs permitted to use this mod, with credits provided?

**Comment by davidjjung** [comment]
Ah, it's an honor! (I'm a big fan of Raspberry-Flavoured.) As stated in the Farmer's Delight Discord, I'm pretty sure that IguanaTweaksReborn has a pretty similar feature (albeit slightly less configurable, and a lot of other features to wade through). You can use the Modrinth jar with credit if needed (it's MIT after all), but do know that there are other options on CurseForge. Thanks for your interest! :]

**Comment by raspmary** [comment]
noticing this very late but thank you very much for the response, using the .jar file was actually exactly why i was asking for permission lol - i would be more than happy to give credit everywhere i can and simply use the file (iguanatweaks seems like a nice alternative, but i'm not fond of having to disable almost all of the mod just to use the one feature i want)
and also, i'm super happy to hear you like RF!! i myself would be honoured to be able to use your mod in the pack :)
