### ISSUE TITLE
Incompatibility with golden buckets (caverns and chasms)

### ISSUE THREAD

**Issue by thelegitdolt** [davidjjung/milkyway#2]
Milking cows with golden buckets doesn't cause a cooldown, and you can even do it when a cooldown is currently active. Works exactly the same as vanilla, actually. 

Since caverns and chasms hasn't released, compatibility is probably not possible, but just wanted to mention it for the future

**Comment by thelegitdolt** [comment]
The item id is `caverns_and_chasms:golden_bucket` and `caverns_and_chasms:golden_milk_bucket` if you want to get it from forge registry

**Comment by davidjjung** [comment]
Ahh, thanks for letting me know. Let this one slip by--should be fixed with an item tag now :)

**Comment by thelegitdolt** [comment]
Looking at your fix-- it is actually possible to milk a cow with a half empty golden milk bucket (since you can put 3 bucketful of liquids in there), which I don't think just tagging the empty golden bucket would cover. Thanks for fixing minecraft issues in the holidays ^^

**Comment by davidjjung** [comment]
Ah whoops--I see, that was why you included both items. Now, is the golden milk bucket actually three separate items, or is it one (with NBT depending on its milk volume?)

**Comment by thelegitdolt** [comment]
it's just one item with nbt

**Comment by davidjjung** [comment]
Gotcha. All I should have to do is add the golden milk bucket--sorry for the hassle, eheh. Hopefully I should be able to put out a fix tomorrow real quick
