### ISSUE TITLE
Last update seem to not be working properlly

### ISSUE THREAD

**Issue by cerealconjugo** [davidjjung/milkyway#3]
last update of **Milkyway** doesn't do anything at all, downgrading fix the problem. I've tried the last update on my modpack and on a fresh install and didn't work either

**Comment by davidjjung** [comment]
Oh, that is so weird--it works in my IDE but not in an actual instance. Did reverting to an older version work?

**Comment by davidjjung** [comment]
Okay, so 1.0.1 *does* work. So weird, I'll try and push a working fix soon. Sorry for the hassle, and thanks for letting me know! So strange

**Comment by cerealconjugo** [comment]
Sorry for not providing you with logs or anything, it was latenight where i live. But thanks for looking at it!!! Love ur mods
