### ISSUE TITLE
C&C compat works as intended?

### ISSUE THREAD

**Issue by cerealconjugo** [davidjjung/milkyway#4]
https://streamable.com/m2yzb6

using golden buckets has an strange behavior

**Comment by davidjjung** [comment]
😭 these golden buckets will be the end of me. I could've sworn that putting them in the appropriate tag would have fixed them... 
 Until I can take a look at how they work by actually putting the mod in my workspace (which I cannot do, as the mod is not out), I'm afraid there's little I can do. I'll have to indicate the incompatibility on my mod's site. Thanks for letting me know, though--if the mod finally releases, I'll work on a fix asap. (I should also put windswept's wooden buckets on the tag too, huh)

**Comment by cerealconjugo** [comment]
Now that C&C is out, its There a Fix in the works?👀

**Comment by davidjjung** [comment]
Yes, hoping to have it out tomorrow or the day after. Thanks for your patience!

**Comment by davidjjung** [comment]
Uploaded Milky Way 1.1.0. Hopefully this is the last version for a while!
