### ISSUE TITLE
Crash with Eetles from Endergetic Expansion beta

### ISSUE THREAD

**Issue by valchiara** [davidjjung/milkyway#5]
The game crashes as soon as an Eetle is loaded.

Minecraft 1.19.2
Milky Way 1.0.3
Endergetic Expansion 4.0.0 (beta 2)

https://pastebin.com/EHurWphA

**Comment by davidjjung** [comment]
Hi--unfortunately, similarly to the other bug with Caverns and Chasms, I can't verify how exactly a bug is happening for a mod that is not formally released (as I can't incorporate it into my workspace). In this case, unless eetles are tagged as milkable, I'm not sure how there could be an incompatibility. If you could test if this crash occurs with *just* Milky Way, Blueprint, and EE 4.0.0 that would be great, but I understand if that's too much of a hassle. Sorry for the inconvenience!

**Comment by valchiara** [comment]
That's what confused me too, as far as I am aware they have no milking interaction. The crash also happens when just Milky Way, Blueprint and EE 4.0.0 are installed.

**Comment by davidjjung** [comment]
Yo, just got a minor hunch on what may have caused eetles to freak out. Let me know if the most recent Milky Way beta (1.0.4) fixes the crash!

**Comment by valchiara** [comment]
The crash still happens with version 1.0.4

**Comment by davidjjung** [comment]
I've made *one* more version (1.0.5) that I hope fixes my 1am coding blunder, and in turn the Endergetic crash. I hope it works :( sorry again for the hassle

**Comment by valchiara** [comment]
The crash no longer occurs 👍
